name: Josh Huang's Blog
markdown: kramdown
layouts_dir: /layouts
permalink: /blog/:year/:month/:day/:title
collections_dir: my_collections
collections: 
  cupcakes:
    output: true

defaults: 
  -  
    scope: 
      path: ""
      type: 
    values: 
      layout: "default"
      
  - 
    scope: 
      path: "_posts"
      type: "posts"
    values: 
      layout: "post"
      