name: Joshua K Huang's website
theme: jekyll-theme-minimal
markdown: kramdown
layouts_dir: /layouts
permalink: /blog/:year/:month/:day/:title
collections_dir: my_collections
collections: 
  cupcakes:
    output: true

