markdown: kramdown
layouts_dir: /layouts
permalink: /blog/:year/:month/:day/:title
collections_dir: my_collections
collections: 
  cupcakes:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
