theme: jekyll-theme-minimal
markdown: kramdown
layouts_dir: /layouts
permalink: /blog/:year/:month/:day/:title
collections_dir: my_collections
collections: 
  cupcakes:
    output: true

defaults:
  -
    scope: 
      path: ""
    values:
      layout: "default"
 -
    scope:
      path: "_posts"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      layout: "post" # overrides previous default layout
      