name: Joshua K Huang's website
markdown: kramdown
layouts_dir: /layouts
permalink: /blog/:year/:month/:day/:title
permalink: /portfolio/:year/:month/:day/:title
collections: 
  cupcakes:
    output: true
